#!/bin/sh
echo "Running pre-commit checks..."
#OS環境差異を吸収するために、実行するgradleを選択する
# OS判定
if [ "$OS" = "Windows_NT" ]; then
    GRADLE_CMD="gradle.bat"
else
    GRADLE_CMD="./gradlew"
fi



#./gradlew clean build
$GRADLE_CMD clean build
RESULT=$?
if [ $RESULT -ne 0 ]; then
    echo "Pre-commit checks failed. Commit aborted."
    exit 1
fi

echo "Running code formatting with Spotless..."
#./gradlew spotlessApply
$GRADLE_CMD spotlessApply
RESULT=$?
if [ $RESULT -ne 0 ]; then
    echo "Code formatting failed. Commit aborted."
    exit 1
fi

# 変更されたファイルを再度ステージングする
git add -u

exit 0