/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.13/samples
 * This project uses @Incubating APIs which are subject to change.
 */


plugins {
    id("java")
    id("jacoco")
    id("application")
    id("com.diffplug.spotless") version "6.25.0"
}

// Spotless configuration for code formatting
spotless {
    java {
        // Use Google's Java formatting style
        googleJavaFormat()
        // Remove unused imports
        importOrder()
        // Remove trailing whitespace
        trimTrailingWhitespace()
        // Ensure files end with a newline
        endWithNewline()
    }
}

application {
    mainClass.set(project.findProperty("mainClass")?.toString() ?: "com.streamConverter.Main")
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}

repositories {
    mavenCentral()
}

dependencies {
    // メインの依存関係
    implementation("org.apache.commons:commons-lang3:3.12.0")
    implementation("commons-io:commons-io:2.15.1")
    implementation("org.slf4j:slf4j-api:2.0.9")
    implementation("ch.qos.logback:logback-classic:1.4.11")

    // JUnit 5 の依存関係（テスト用）
    testImplementation("org.junit.jupiter:junit-jupiter:5.9.3")
}

tasks.test {
    // JUnit 5 を使うための設定
    useJUnitPlatform()
    
    // テスト実行時の詳細ログを表示
    testLogging {
        events("passed", "skipped", "failed")
        showStandardStreams = true
    }
    
    // テスト完了後にJaCoCoレポートを生成
    finalizedBy(tasks.jacocoTestReport)
}

// JaCoCoレポートの設定
tasks.jacocoTestReport {
    reports {
        xml.required.set(true)
        html.required.set(true)
    }
    
    // テスト後にレポートを生成
    dependsOn(tasks.test)
}
