/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.13/samples
 * This project uses @Incubating APIs which are subject to change.
 */

import com.github.spotbugs.snom.SpotBugsTask
import java.math.BigDecimal
import java.io.File
import java.io.Serializable
import java.net.URLClassLoader
import javax.xml.parsers.DocumentBuilderFactory
import org.gradle.api.Action
import org.gradle.api.plugins.quality.Pmd
import org.gradle.api.Task
import org.gradle.api.tasks.testing.Test
import org.gradle.api.tasks.testing.TestDescriptor
import org.gradle.api.tasks.testing.TestListener
import org.gradle.api.tasks.testing.TestResult
import org.gradle.api.tasks.testing.logging.TestExceptionFormat
import org.gradle.api.tasks.testing.logging.TestLogEvent


plugins {
    id("java")
    id("jacoco")
    id("application")
    id("pmd")
    id("com.github.spotbugs") version "6.5.1"
    id("com.diffplug.spotless") version "8.4.0"
    id("info.solidsoft.pitest") version "1.19.0"
    id("org.springframework.boot") version "4.0.6"
    id("io.spring.dependency-management") version "1.1.7"
}

class TestSkipReasonResolver(private val classpathEntries: Iterable<File>) {
    fun resolve(testDescriptor: TestDescriptor): String? {
        val className = testDescriptor.className ?: return null
        val methodName = testDescriptor.name.removeSuffix("()")

        return URLClassLoader(
            classpathEntries.map { it.toURI().toURL() }.toTypedArray(),
            javaClass.classLoader
        ).use { classLoader ->
            runCatching {
                val testClass = classLoader.loadClass(className)
                findDisabledReason(testClass, methodName)
            }.getOrNull()
        }
    }

    private fun findDisabledReason(testClass: Class<*>, methodName: String): String? {
        val method = testClass.declaredMethods.firstOrNull { it.name == methodName }

        return extractReason(method?.annotations?.asList())
            ?: extractReason(testClass.annotations.asList())
    }

    private fun extractReason(annotations: List<Annotation>?): String? {
        if (annotations == null) {
            return null
        }

        annotations.forEach { annotation ->
            val annotationType = annotation.annotationClass.java
            if (!annotationType.name.startsWith("org.junit.jupiter.api.condition.")
                && annotationType.name != "org.junit.jupiter.api.Disabled"
            ) {
                return@forEach
            }

            listOf("disabledReason", "value", "reason").forEach { attributeName ->
                val attribute = annotationType.methods.firstOrNull { it.name == attributeName } ?: return@forEach
                val rawValue = runCatching { attribute.invoke(annotation) }.getOrNull() ?: return@forEach
                val rendered = renderAnnotationValue(rawValue).trim()
                if (rendered.isNotEmpty()) {
                    return rendered
                }
            }

            val fallback = annotation.toString()
                .substringAfter("(")
                .substringBeforeLast(")")
                .trim()
            if (fallback.isNotEmpty()) {
                return fallback
            }
        }

        return null
    }

    private fun renderAnnotationValue(value: Any): String {
        return when (value) {
            is Array<*> -> value.joinToString(", ") { it.toString() }
            else -> value.toString()
        }
    }
}

object QualityReportPrinter {
    private const val MAX_DETAILS = 40

    private fun parseXmlDocument(reportFile: File) = DocumentBuilderFactory.newInstance()
        .apply {
            setFeature("http://apache.org/xml/features/disallow-doctype-decl", true)
            setFeature("http://xml.org/sax/features/external-general-entities", false)
            setFeature("http://xml.org/sax/features/external-parameter-entities", false)
            isXIncludeAware = false
            isExpandEntityReferences = false
        }
        .newDocumentBuilder()
        .parse(reportFile)

    fun summarizePmdReport(taskPath: String, reportFile: File) {
        if (!reportFile.isFile) {
            return
        }

        val document = parseXmlDocument(reportFile)
        val violations = document.getElementsByTagName("violation")
        if (violations.length == 0) {
            println("PMD summary for $taskPath: no violations")
            return
        }

        println("PMD summary for $taskPath: ${violations.length} violation(s)")
        val ruleCounts = linkedMapOf<String, Int>()
        val detailLimit = minOf(violations.length, MAX_DETAILS)
        for (index in 0 until violations.length) {
            val violation = violations.item(index)
            val filePath = violation.parentNode?.attributes?.getNamedItem("name")?.nodeValue ?: "<unknown>"
            val line = violation.attributes?.getNamedItem("beginline")?.nodeValue ?: "?"
            val rule = violation.attributes?.getNamedItem("rule")?.nodeValue ?: "unknown-rule"
            val message = violation.textContent.trim().replace(Regex("\\s+"), " ")
            ruleCounts[rule] = (ruleCounts[rule] ?: 0) + 1
            if (index < detailLimit) {
                println("  $filePath:$line [$rule] $message")
            }
        }

        if (violations.length > detailLimit) {
            println("  ... ${violations.length - detailLimit} more violation(s) omitted from console output")
        }

        println("  Top rules:")
        ruleCounts.entries
            .sortedByDescending { it.value }
            .take(10)
            .forEach { (rule, count) ->
                println("    $count $rule")
            }

        println("  Full XML: ${reportFile.absolutePath}")
    }

    fun summarizeSpotBugsReport(taskPath: String, reportFile: File) {
        if (!reportFile.isFile) {
            return
        }

        val document = parseXmlDocument(reportFile)
        val bugs = document.getElementsByTagName("BugInstance")
        if (bugs.length == 0) {
            println("SpotBugs summary for $taskPath: no findings")
            return
        }

        println("SpotBugs summary for $taskPath: ${bugs.length} finding(s)")
        val typeCounts = linkedMapOf<String, Int>()
        val detailLimit = minOf(bugs.length, MAX_DETAILS)
        for (index in 0 until bugs.length) {
            val bug = bugs.item(index)
            val type = bug.attributes?.getNamedItem("type")?.nodeValue ?: "unknown-type"
            val priority = bug.attributes?.getNamedItem("priority")?.nodeValue ?: "?"
            val sourceLine = bug.childNodes?.let { children ->
                (0 until children.length)
                    .map { children.item(it) }
                    .firstOrNull { it.nodeName == "SourceLine" }
            }
            val filePath = sourceLine?.attributes?.getNamedItem("sourcepath")?.nodeValue ?: "<unknown>"
            val line = sourceLine?.attributes?.getNamedItem("start")?.nodeValue ?: "?"
            val longMessage = bug.childNodes?.let { children ->
                (0 until children.length)
                    .map { children.item(it) }
                    .firstOrNull { it.nodeName == "LongMessage" }
                    ?.textContent
            }?.trim()?.replace(Regex("\\s+"), " ") ?: "No description"
            typeCounts[type] = (typeCounts[type] ?: 0) + 1
            if (index < detailLimit) {
                println("  $filePath:$line [$type priority=$priority] $longMessage")
            }
        }

        if (bugs.length > detailLimit) {
            println("  ... ${bugs.length - detailLimit} more finding(s) omitted from console output")
        }

        println("  Top bug types:")
        typeCounts.entries
            .sortedByDescending { it.value }
            .take(10)
            .forEach { (type, count) ->
                println("    $count $type")
            }

        println("  Full XML: ${reportFile.absolutePath}")
    }
}

class PmdSummaryAction(
    private val taskPath: String,
    private val reportFile: File
) : Action<Task>, Serializable {
    override fun execute(task: Task) {
        QualityReportPrinter.summarizePmdReport(taskPath, reportFile)
    }
}

class SpotBugsSummaryAction(
    private val taskPath: String,
    private val reportFile: File
) : Action<Task>, Serializable {
    override fun execute(task: Task) {
        QualityReportPrinter.summarizeSpotBugsReport(taskPath, reportFile)
    }
}

fun Test.configureReadableTestOutput() {
    val verboseTests = providers.systemProperty("test.verbose")
        .orElse(providers.gradleProperty("test.verbose"))
        .map(String::toBoolean)
        .getOrElse(false)

    testLogging {
        events = setOf(TestLogEvent.FAILED, TestLogEvent.SKIPPED)
        showStandardStreams = verboseTests
        showExceptions = true
        showCauses = true
        showStackTraces = verboseTests
        exceptionFormat = if (verboseTests) {
            TestExceptionFormat.FULL
        } else {
            TestExceptionFormat.SHORT
        }
    }

    addTestListener(object : TestListener {
        override fun beforeSuite(suite: TestDescriptor) = Unit

        override fun beforeTest(testDescriptor: TestDescriptor) = Unit

        override fun afterTest(testDescriptor: TestDescriptor, result: TestResult) {
            if (result.resultType == TestResult.ResultType.SKIPPED) {
                val reason = result.exceptions
                    .mapNotNull { it.message?.trim() }
                    .firstOrNull()
                    ?: TestSkipReasonResolver(testClassesDirs.files + classpath.files).resolve(testDescriptor)
                    ?: "No skip reason provided"
                logger.lifecycle("Skipped: ${testDescriptor.className}.${testDescriptor.name} -> $reason")
            }
        }

        override fun afterSuite(suite: TestDescriptor, result: TestResult) {
            if (suite.parent == null) {
                logger.lifecycle(
                    "Test summary: ${result.resultType} " +
                        "(${result.testCount} total, ${result.successfulTestCount} passed, " +
                        "${result.failedTestCount} failed, ${result.skippedTestCount} skipped)"
                )
            }
        }
    })
}

// Main class configuration
// Example run tasks are defined in :streamconverter-examples

// Benchmark tasks
tasks.register<Test>("benchmarkLargeData") {
    group = "benchmark"
    description = "Run large data benchmark tests (5GB/50MB target)"
    useJUnitPlatform {
        includeTags("benchmark", "large-data")
    }
    include("**/benchmark/**")
    
    // 5GBテスト用にヒープサイズを大きく設定
    jvmArgs("-Xmx3g", "-Xms1g")
    
}
tasks.register<Test>("benchmarkInfrastructure") {
    group = "benchmark"
    description = "Run benchmark infrastructure tests"
    useJUnitPlatform()
    include("**/BenchmarkInfrastructureTest*")
    
    jvmArgs("-Xmx1g", "-Xms512m")
    
}

tasks.register<Test>("benchmarkMemoryEfficiency") {
    group = "benchmark"
    description = "Run memory efficiency benchmarks"
    useJUnitPlatform()
    include("**/MemoryEfficiencyTest*")
    // Increase heap size for memory efficiency tests
    jvmArgs("-Xms1g", "-Xmx2g")
}

tasks.register<Test>("benchmarkAll") {
    group = "benchmark"
    description = "Run all benchmark tests"
    useJUnitPlatform()
    include("**/benchmark/**/*Test*", "**/MemoryEfficiencyTest*")
    // Increase heap size for all benchmarks
    jvmArgs("-Xms1g", "-Xmx2g")
}

// Spotless configuration for code formatting
spotless {
    java {
        // Use Google's Java formatting style
        googleJavaFormat()
        // Remove unused imports
        importOrder()
        // Remove trailing whitespace
        trimTrailingWhitespace()
        // Ensure files end with a newline
        endWithNewline()
    }
}

application {
    mainClass.set(project.findProperty("mainClass")?.toString() ?: "com.streamconverter.Main")
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21

    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
        // Automatically detect available Java 21 installations
    }
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}

repositories {
    mavenCentral()
}

// Root project has no direct runtime sources; keep dependencies in subprojects

tasks.test {
    // JUnit 5 を使うための設定
    useJUnitPlatform {
        // ベンチマークテストと known-bug テストを通常のテスト実行から除外
        excludeTags("benchmark", "large-data", "known-bug")
    }

    // クラス名・パスパターンでもベンチマーク系テストを除外
    exclude("**/benchmark/**", "**/*Benchmark*", "**/MemoryEfficiencyTest*")
    
    // メモリ効率テスト用にJVMヒープサイズを設定
    jvmArgs("-Xmx1g", "-Xms512m")
    
    // テスト完了後にJaCoCoレポートを生成
    finalizedBy(tasks.jacocoTestReport)
    // テスト実行後にjavadocを生成
    finalizedBy(tasks.javadoc)
}

// JaCoCoレポートの設定
tasks.jacocoTestReport {
    reports {
        html.required.set(true)
        xml.required.set(true)
        csv.required.set(false)
    }
    
    // テスト後にレポートを生成
    // dependsOn(tasks.test)
}

// PITレポートの設定
tasks.pitest {
    targetClasses.set(listOf("com.streamconverter.*")) // テスト対象のクラスを指定
    outputFormats.set(listOf("HTML")) // 出力形式を指定
    // タイムアウト設定を追加
    timeoutConstInMillis.set(10000) // 10秒でタイムアウト
    timeoutFactor.set(BigDecimal("1.5")) // 1.5倍のマージン
    // 対象クラスを絞り込んでパフォーマンスを向上
    excludedClasses.set(listOf(
        "com.streamconverter.examples.*", // サンプルコードを除外
        "com.streamconverter.demo.*"      // デモコードを除外
    ))
    // テスト後にレポートを生成
    // dependsOn(tasks.test)
}

// javadocタスクの設定
tasks.javadoc {
    options.encoding = "UTF-8"
    options.memberLevel = org.gradle.external.javadoc.JavadocMemberLevel.PROTECTED
    setDestinationDir(file("build/docs/javadoc"))
}

// spotlessCheck タスクを無効化
tasks.named("spotlessCheck") {
    enabled = false
}

// PMD configuration for code smell detection
pmd {
    isConsoleOutput = false
    toolVersion = "7.16.0"
    rulesMinimumPriority = 5
    ruleSetFiles = files("config/pmd/ruleset.xml")
    ruleSets = emptyList()
}

// PMD task configuration
tasks.pmdMain {
    reports {
        xml.required.set(true)
        html.required.set(true)
    }
    exclude("**/examples/**", "**/demo/**")
}


// SpotBugs configuration for bug pattern detection
spotbugs {
    toolVersion.set("4.8.6")
    effort.set(com.github.spotbugs.snom.Effort.MAX)
    reportLevel.set(com.github.spotbugs.snom.Confidence.MEDIUM)
    excludeFilter.set(file("spotbugs-exclude.xml"))
}

// SpotBugs task configuration
tasks.spotbugsMain {
    reports.create("html") {
        required.set(true)
        outputLocation.set(file("build/reports/spotbugs/main.html"))
    }
    reports.create("xml") {
        required.set(true) 
        outputLocation.set(file("build/reports/spotbugs/main.xml"))
    }
}

tasks.spotbugsTest {
    reports.create("html") {
        required.set(true)
        outputLocation.set(file("build/reports/spotbugs/test.html"))
    }
    reports.create("xml") {
        required.set(true) 
        outputLocation.set(file("build/reports/spotbugs/test.xml"))
    }
}

// check タスクの実行時に spotlessApply を依存タスクとして実行する
tasks.named("check") {
    dependsOn("spotlessApply")
}

// Root project configuration for multi-module build
allprojects {
    group = "com.streamconverter"
    version = "0.0.0"

    tasks.withType<Test>().configureEach {
        configureReadableTestOutput()
        systemProperty("skipNetworkTests", System.getProperty("skipNetworkTests", "true"))
    }

    tasks.withType<Pmd>().configureEach {
        reports.xml.required.set(true)
        val reportSuffix = name.removePrefix("pmd")
            .replaceFirstChar { it.lowercase() }
        val reportFile = project.layout.buildDirectory
            .file("reports/pmd/$reportSuffix.xml")
            .get()
            .asFile
        doLast(PmdSummaryAction(path, reportFile))
    }

    tasks.withType<SpotBugsTask>().configureEach {
        val reportSuffix = name.removePrefix("spotbugs")
            .replaceFirstChar { it.lowercase() }
        val reportFile = project.layout.buildDirectory
            .file("reports/spotbugs/$reportSuffix.xml")
            .get()
            .asFile
        doLast(SpotBugsSummaryAction(path, reportFile))
    }
}

tasks.register("buildAll") {
    group = "build"
    description = "Build all modules"
    dependsOn(subprojects.map { it.tasks.named("build") })
}

tasks.register("testAll") {
    group = "verification"
    description = "Test all modules"
    dependsOn(subprojects.map { it.tasks.named("test") })
}

// Unified Javadoc generation for all modules
tasks.register<Javadoc>("javadocAll") {
    group = "documentation"
    description = "Generate unified Javadoc for all modules"

    // Aggregate source from all modules
    val allSourceSets = subprojects.map { it.extensions.getByType<SourceSetContainer>().main.get().allJava }
    source(allSourceSets)

    // Set dependencies to ensure subprojects are built first
    dependsOn(subprojects.map { "${it.path}:classes" })

    // Use Provider API for lazy configuration resolution
    val allClasspaths = provider {
        subprojects.flatMap { subproject ->
            subproject.configurations.getByName("compileClasspath").files +
            subproject.tasks.named("jar", Jar::class.java).get().outputs.files.files
        }
    }

    classpath = files(allClasspaths)

    // Configure for unified output
    options.encoding = "UTF-8"
    options.memberLevel = org.gradle.external.javadoc.JavadocMemberLevel.PROTECTED
    setDestinationDir(file("build/docs/javadoc"))

    // Javadoc options for better presentation
    if (options is StandardJavadocDocletOptions) {
        (options as StandardJavadocDocletOptions).apply {
            windowTitle("StreamConverter $version API")
            docTitle("StreamConverter $version API Documentation")
            author(true)
            use(true)
            version(true)
            splitIndex(true)
            linkSource(true)
            addStringOption("Xdoclint:none", "-quiet")
        }
    }

    doLast {
        println("✅ Unified Javadoc generated:")
        println("   📖 Location: build/docs/javadoc/index.html")
        println("   🚀 Ready for GitHub Actions deployment")
    }
}
