/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.13/samples
 * This project uses @Incubating APIs which are subject to change.
 */

import java.math.BigDecimal


plugins {
    id("java")
    id("jacoco")
    id("application")
    id("pmd")
    id("com.github.spotbugs") version "6.4.8"
    id("com.diffplug.spotless") version "8.1.0"
    id("info.solidsoft.pitest") version "1.19.0-rc.2"
    id("org.springframework.boot") version "4.0.1"
    id("io.spring.dependency-management") version "1.1.7"
}

// Main class configuration
// Example run tasks are defined in :streamconverter-examples

// Benchmark tasks
tasks.register<Test>("benchmarkLargeData") {
    group = "benchmark"
    description = "Run large data benchmark tests (5GB/50MB target)"
    useJUnitPlatform {
        includeTags("benchmark", "large-data")
    }
    include("**/benchmark/**")
    
    // 5GBテスト用にヒープサイズを大きく設定
    jvmArgs("-Xmx3g", "-Xms1g")
    
    testLogging {
        events("skipped", "failed")
        showStandardStreams = true
        exceptionFormat = org.gradle.api.tasks.testing.logging.TestExceptionFormat.FULL
    }
}
tasks.register<Test>("benchmarkInfrastructure") {
    group = "benchmark"
    description = "Run benchmark infrastructure tests"
    useJUnitPlatform()
    include("**/BenchmarkInfrastructureTest*")
    
    jvmArgs("-Xmx1g", "-Xms512m")
    
    testLogging {
        events("skipped", "failed")
        showStandardStreams = true
    }
}

tasks.register<Test>("benchmarkMemoryEfficiency") {
    group = "benchmark"
    description = "Run memory efficiency benchmarks"
    useJUnitPlatform()
    include("**/MemoryEfficiencyTest*")
    testLogging {
        events("skipped", "failed")
        showStandardStreams = true
    }
    // Increase heap size for memory efficiency tests
    jvmArgs("-Xms1g", "-Xmx2g")
}

tasks.register<Test>("benchmarkAll") {
    group = "benchmark"
    description = "Run all benchmark tests"
    useJUnitPlatform()
    include("**/benchmark/**/*Test*", "**/MemoryEfficiencyTest*")
    testLogging {
        events("skipped", "failed")
        showStandardStreams = true
    }
    // Increase heap size for all benchmarks
    jvmArgs("-Xms1g", "-Xmx2g")
}

// Spotless configuration for code formatting
spotless {
    java {
        // Use Google's Java formatting style
        googleJavaFormat()
        // Remove unused imports
        importOrder()
        // Remove trailing whitespace
        trimTrailingWhitespace()
        // Ensure files end with a newline
        endWithNewline()
    }
}

application {
    mainClass.set(project.findProperty("mainClass")?.toString() ?: "com.streamconverter.Main")
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21

    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
        // Automatically detect available Java 21 installations
    }
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}

repositories {
    mavenCentral()
}

// Root project has no direct runtime sources; keep dependencies in subprojects

tasks.test {
    // JUnit 5 を使うための設定
    useJUnitPlatform {
        // ベンチマークテストを通常のテスト実行から除外
        excludeTags("benchmark", "large-data")
    }

    // クラス名・パスパターンでもベンチマーク系テストを除外
    exclude("**/benchmark/**", "**/*Benchmark*", "**/MemoryEfficiencyTest*")
    
    // メモリ効率テスト用にJVMヒープサイズを設定
    jvmArgs("-Xmx1g", "-Xms512m")
    
    // テスト実行時の詳細ログを表示
    testLogging {
        events("skipped", "failed")
        showStandardStreams = true
    }
    
    // テスト完了後にJaCoCoレポートを生成
    finalizedBy(tasks.jacocoTestReport)
    // テスト実行後にjavadocを生成
    finalizedBy(tasks.javadoc)
}

// JaCoCoレポートの設定
tasks.jacocoTestReport {
    reports {
        html.required.set(true)
        xml.required.set(true)
        csv.required.set(false)
    }
    
    // テスト後にレポートを生成
    // dependsOn(tasks.test)
}

// PITレポートの設定
tasks.pitest {
    targetClasses.set(listOf("com.streamconverter.*")) // テスト対象のクラスを指定
    outputFormats.set(listOf("HTML")) // 出力形式を指定
    // タイムアウト設定を追加
    timeoutConstInMillis.set(10000) // 10秒でタイムアウト
    timeoutFactor.set(BigDecimal("1.5")) // 1.5倍のマージン
    // 対象クラスを絞り込んでパフォーマンスを向上
    excludedClasses.set(listOf(
        "com.streamconverter.examples.*", // サンプルコードを除外
        "com.streamconverter.demo.*"      // デモコードを除外
    ))
    // テスト後にレポートを生成
    // dependsOn(tasks.test)
}

// javadocタスクの設定
tasks.javadoc {
    options.encoding = "UTF-8"
    options.memberLevel = org.gradle.external.javadoc.JavadocMemberLevel.PROTECTED
    setDestinationDir(file("build/docs/javadoc"))
}

// spotlessCheck タスクを無効化
tasks.named("spotlessCheck") {
    enabled = false
}

// PMD configuration for code smell detection
pmd {
    isConsoleOutput = false
    toolVersion = "7.16.0"
    rulesMinimumPriority = 5
    ruleSets = listOf(
        "category/java/bestpractices.xml",
        "category/java/codestyle.xml",
        "category/java/design.xml",
        "category/java/errorprone.xml",
        "category/java/performance.xml",
        "category/java/security.xml"
    )
}

// PMD task configuration
tasks.pmdMain {
    reports {
        xml.required.set(true)
        html.required.set(true)
    }
    exclude("**/examples/**", "**/demo/**")
}

// SpotBugs configuration for bug pattern detection
spotbugs {
    toolVersion.set("4.8.6")
    effort.set(com.github.spotbugs.snom.Effort.MAX)
    reportLevel.set(com.github.spotbugs.snom.Confidence.MEDIUM)
    excludeFilter.set(file("spotbugs-exclude.xml"))
}

// SpotBugs task configuration
tasks.spotbugsMain {
    ignoreFailures = true // SpotBugs違反があってもビルドを継続
    reports.create("html") {
        required.set(true)
        outputLocation.set(file("build/reports/spotbugs/main.html"))
    }
    reports.create("xml") {
        required.set(true) 
        outputLocation.set(file("build/reports/spotbugs/main.xml"))
    }
}

tasks.spotbugsTest {
    ignoreFailures = true // テストコードのSpotBugs違反があってもビルドを継続
    reports.create("html") {
        required.set(true)
        outputLocation.set(file("build/reports/spotbugs/test.html"))
    }
    reports.create("xml") {
        required.set(true) 
        outputLocation.set(file("build/reports/spotbugs/test.xml"))
    }
}

// check タスクの実行時に spotlessApply を依存タスクとして実行する
tasks.named("check") {
    dependsOn("spotlessApply")
}

// Root project configuration for multi-module build
allprojects {
    group = "com.streamconverter"
    version = "0.0.0"

    tasks.withType<Test>().configureEach {
        systemProperty("skipNetworkTests", System.getProperty("skipNetworkTests", "true"))
    }
}

tasks.register("buildAll") {
    group = "build"
    description = "Build all modules"
    dependsOn(subprojects.map { it.tasks.named("build") })
}

tasks.register("testAll") {
    group = "verification"
    description = "Test all modules"
    dependsOn(subprojects.map { it.tasks.named("test") })
}

// Unified Javadoc generation for all modules
tasks.register<Javadoc>("javadocAll") {
    group = "documentation"
    description = "Generate unified Javadoc for all modules"

    // Aggregate source from all modules
    val allSourceSets = subprojects.map { it.extensions.getByType<SourceSetContainer>().main.get().allJava }
    source(allSourceSets)

    // Set dependencies to ensure subprojects are built first
    dependsOn(subprojects.map { "${it.path}:classes" })

    // Use Provider API for lazy configuration resolution
    val allClasspaths = provider {
        subprojects.flatMap { subproject ->
            subproject.configurations.getByName("compileClasspath").files +
            subproject.tasks.named("jar", Jar::class.java).get().outputs.files.files
        }
    }

    classpath = files(allClasspaths)

    // Configure for unified output
    options.encoding = "UTF-8"
    options.memberLevel = org.gradle.external.javadoc.JavadocMemberLevel.PROTECTED
    setDestinationDir(file("build/docs/javadoc"))

    // Javadoc options for better presentation
    if (options is StandardJavadocDocletOptions) {
        (options as StandardJavadocDocletOptions).apply {
            windowTitle("StreamConverter $version API")
            docTitle("StreamConverter $version API Documentation")
            author(true)
            use(true)
            version(true)
            splitIndex(true)
            linkSource(true)
            addStringOption("Xdoclint:none", "-quiet")
        }
    }

    doLast {
        println("✅ Unified Javadoc generated:")
        println("   📖 Location: build/docs/javadoc/index.html")
        println("   🚀 Ready for GitHub Actions deployment")
    }
}

