/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.13/userguide/multi_project_builds.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "StreamConverter"

// Disable parallel execution when running inside environments that expect sequential configuration evaluation.
val disableParallelEnvFlags =
    listOf("GRADLE_BUILD_SERVER", "CI", "GITHUB_ACTIONS")
        .mapNotNull { key ->
            System.getenv(key)?.takeIf { value ->
                value.equals("true", ignoreCase = true) || value == "1"
            }?.let { key }
        }

if (disableParallelEnvFlags.isNotEmpty()) {
    val propertyName = "org.gradle.parallel"
    val propertyAlreadyFalse =
        System.getProperty(propertyName)?.equals("false", ignoreCase = true) == true
    if (!propertyAlreadyFalse) {
        System.setProperty(propertyName, "false")
        println(
            "Gradle parallel project execution disabled due to " +
                disableParallelEnvFlags.joinToString() +
                " environment flag(s)."
        )
    }
}

pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        google()
    }
}

// Multi-module configuration
include("streamconverter-core")
include("streamconverter-web")
include("streamconverter-examples") 
include("streamconverter-tools")

// Project configuration
project(":streamconverter-core").projectDir = file("streamconverter-core")
project(":streamconverter-web").projectDir = file("streamconverter-web")
project(":streamconverter-examples").projectDir = file("streamconverter-examples")
project(":streamconverter-tools").projectDir = file("streamconverter-tools")
