/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.13/userguide/multi_project_builds.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "StreamConverter"

pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        google()
    }
}

// Multi-module configuration
include("streamconverter-core")
include("streamconverter-web")
include("streamconverter-examples") 
include("streamconverter-tools")

// Project configuration
project(":streamconverter-core").projectDir = file("streamconverter-core")
project(":streamconverter-web").projectDir = file("streamconverter-web")
project(":streamconverter-examples").projectDir = file("streamconverter-examples")
project(":streamconverter-tools").projectDir = file("streamconverter-tools")
