/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.13/userguide/multi_project_builds.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "StreamConverter"
// settings.gradle.kts

pluginManagement {
    repositories {
        // Spotless プラグインなど、plugins.gradle.org にあるものを探す
        gradlePluginPortal()

        // 必要なら他のリポジトリも順に追加
        mavenCentral()
        google()
    }
}
