name: Code Quality

on:
  pull_request:
    branches: [ main, master, develop ]
  push:
    branches: [ main, master, develop ]

jobs:
  # Check code style, run lint and tests
  code-quality:
    name: Code Quality and Tests
    permissions:
      contents: read
      pull-requests: write
    strategy:
      fail-fast: false
      matrix: # mac osは特に高いので、コスト面の問題でubuntu以外を偶にしか走らないように設定する必要がある場合がある。
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew (Linux/Mac only)
        if: runner.os != 'Windows'
        run: chmod +x gradlew
        
      - name: Apply code style with Spotless
        run: ./gradlew spotlessApply
        
      - name: Build and run tests
        run: ${{ runner.os == 'Windows' && 'gradlew.bat' || './gradlew' }} build -Dfile.encoding=UTF-8
