name: Code Quality

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

jobs:
  # Check code style, run lint and tests
  code-quality:
    name: Code Quality and Tests
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Check code style with Spotless
        run: ./gradlew spotlessCheck
        
      - name: Run lint
        run: ./gradlew lint
        continue-on-error: true
        
      - name: Build and run tests
        run: ./gradlew build
